### PR TITLE
[21] Update URL to https (WIP)

### LINKED ISSUE #21: Needs to support HTTPS
Helper currently fails with a redirect - it needs to support HTTPS

### PR DESCRIPTION
**Pull request by MeliaBurnley**
Fixes #21

### CODE REVIEW

**Comment by akosasante** [comment]
🎉 @ejhobbs , any chance of merging this change for this year's advent of code?

**Comment by ejhobbs** [comment]
hi! Thanks for stopping by. The project is very unmaintained at this point, my last commit was ~3 years ago and I'm not sure i've been able to write a line of elixir since...

Anyway, main takeaway: Yes i can merge this, but I've forgotten how to do the other parts (updating hex etc.). If you'd like, I can transfer the ownership of the project and you can keep it going? The code all works, the test suite however is quite broken (I don't remember if it ever worked really).

**Comment by akosasante** [comment]
Thanks for the quick response! Sure, I'd be happy to take over the project 😄

**Comment by akosasante** [comment]
@danielburnley As Edward mentioned there's some failing tests in the repo; but I'll merge your PR and work on fixing the failing tests separately 😄

**Pull request merged**
